sudo: false
language: android
env:
  global:
  - ANDROID_API_LEVEL=23
  - EMULATOR_API_LEVEL=21
  - ANDROID_BUILD_TOOLS_VERSION=23.0.3
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - addon-google_apis-google-$ANDROID_API_LEVEL
  - addon-google_apis-google-$EMULATOR_API_LEVEL
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL
before_script:
- cd FindLunchApp
- echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi
  $ANDROID_ABI --tag $ANDROID_TAG
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
deploy:
  provider: releases
  api_key:
    secure: Atcd3zL25v/GVxJSa/FqV8uHux2TplIX5eT8yUnq2MKG5PguSZr+x+83xJmbN7dl+uNhArQfJQ6ztPIWY8+v7ftabtUvU/shyuHSzWOcKSj3G+c/M14MGeUk2HfRxkfPOBbScwvbPLXlRg45/lmehZHRMQhN/BlvEbMkXlO8Asxvg7a3/YE7FOxvFI+uxY3R85PK91RdOc3olaAKzNo3eb7eySAQMeg9hEPbhsxmDHufAC6ttneEoxRrh2F1h3+T0pDI2D3fLJ+UgOEGrluzaGPzwzku/LR+5aXdNuL1Gg87QsMh6SiZ6qJ8nyTzfMAkeme9TjS5RTvVwt5PZF8t1lQwkYXscmKdKepsHkrCfo6DEK3BHVMDsHl3Ulf0V73j40zw7N3R1+BlIqQmfxVCrfLeGj/7Cet98ptjQQx9xkf4CrUKqFh5G2n9KiXrrimmYcJWLS4jibKOXFJ+1aefq2vNUufECkCiMOw+SzIxE50j20/38JtYmrxO7ymxKS3ZwJeFzY9v8q5QQMlWa1Mw3+rgPNgMaLBz+XXP8+tUvZn1KYeOyWAwkOK2anDiaRcCxs4JsmhdcFecbIcMut9vOkUjlK4folAtIhse0Rs7grnXjL5+fzSAG4T2+64iqxA6PGc830xjhJQA5uoQ/ClvWtN3eqLlzUbMLAJGkZcXOwU=
  file: app/build/outputs/apk/app*release*.apk
  skip_cleanup: true
  on:
    repo: CCWI/findlunch
    branch: feature_travis-ci-findlunchapp
